#ifndef _BFLB_UART_H_
#define _BFLB_UART_H_

/* 0x0 : utx_config */
#define UART_UTX_CONFIG_OFFSET                                  (0x0)
#define UART_CR_UTX_EN                                          UART_CR_UTX_EN
#define UART_CR_UTX_EN_POS                                      (0U)
#define UART_CR_UTX_EN_LEN                                      (1U)
#define UART_CR_UTX_EN_MSK                                      (((1U<<UART_CR_UTX_EN_LEN)-1)<<UART_CR_UTX_EN_POS)
#define UART_CR_UTX_EN_UMSK                                     (~(((1U<<UART_CR_UTX_EN_LEN)-1)<<UART_CR_UTX_EN_POS))
#define UART_CR_UTX_CTS_EN                                      UART_CR_UTX_CTS_EN
#define UART_CR_UTX_CTS_EN_POS                                  (1U)
#define UART_CR_UTX_CTS_EN_LEN                                  (1U)
#define UART_CR_UTX_CTS_EN_MSK                                  (((1U<<UART_CR_UTX_CTS_EN_LEN)-1)<<UART_CR_UTX_CTS_EN_POS)
#define UART_CR_UTX_CTS_EN_UMSK                                 (~(((1U<<UART_CR_UTX_CTS_EN_LEN)-1)<<UART_CR_UTX_CTS_EN_POS))
#define UART_CR_UTX_FRM_EN                                      UART_CR_UTX_FRM_EN
#define UART_CR_UTX_FRM_EN_POS                                  (2U)
#define UART_CR_UTX_FRM_EN_LEN                                  (1U)
#define UART_CR_UTX_FRM_EN_MSK                                  (((1U<<UART_CR_UTX_FRM_EN_LEN)-1)<<UART_CR_UTX_FRM_EN_POS)
#define UART_CR_UTX_FRM_EN_UMSK                                 (~(((1U<<UART_CR_UTX_FRM_EN_LEN)-1)<<UART_CR_UTX_FRM_EN_POS))
#define UART_CR_UTX_LIN_EN                                      UART_CR_UTX_LIN_EN
#define UART_CR_UTX_LIN_EN_POS                                  (3U)
#define UART_CR_UTX_LIN_EN_LEN                                  (1U)
#define UART_CR_UTX_LIN_EN_MSK                                  (((1U<<UART_CR_UTX_LIN_EN_LEN)-1)<<UART_CR_UTX_LIN_EN_POS)
#define UART_CR_UTX_LIN_EN_UMSK                                 (~(((1U<<UART_CR_UTX_LIN_EN_LEN)-1)<<UART_CR_UTX_LIN_EN_POS))
#define UART_CR_UTX_PRT_EN                                      UART_CR_UTX_PRT_EN
#define UART_CR_UTX_PRT_EN_POS                                  (4U)
#define UART_CR_UTX_PRT_EN_LEN                                  (1U)
#define UART_CR_UTX_PRT_EN_MSK                                  (((1U<<UART_CR_UTX_PRT_EN_LEN)-1)<<UART_CR_UTX_PRT_EN_POS)
#define UART_CR_UTX_PRT_EN_UMSK                                 (~(((1U<<UART_CR_UTX_PRT_EN_LEN)-1)<<UART_CR_UTX_PRT_EN_POS))
#define UART_CR_UTX_PRT_SEL                                     UART_CR_UTX_PRT_SEL
#define UART_CR_UTX_PRT_SEL_POS                                 (5U)
#define UART_CR_UTX_PRT_SEL_LEN                                 (1U)
#define UART_CR_UTX_PRT_SEL_MSK                                 (((1U<<UART_CR_UTX_PRT_SEL_LEN)-1)<<UART_CR_UTX_PRT_SEL_POS)
#define UART_CR_UTX_PRT_SEL_UMSK                                (~(((1U<<UART_CR_UTX_PRT_SEL_LEN)-1)<<UART_CR_UTX_PRT_SEL_POS))
#define UART_CR_UTX_IR_EN                                       UART_CR_UTX_IR_EN
#define UART_CR_UTX_IR_EN_POS                                   (6U)
#define UART_CR_UTX_IR_EN_LEN                                   (1U)
#define UART_CR_UTX_IR_EN_MSK                                   (((1U<<UART_CR_UTX_IR_EN_LEN)-1)<<UART_CR_UTX_IR_EN_POS)
#define UART_CR_UTX_IR_EN_UMSK                                  (~(((1U<<UART_CR_UTX_IR_EN_LEN)-1)<<UART_CR_UTX_IR_EN_POS))
#define UART_CR_UTX_IR_INV                                      UART_CR_UTX_IR_INV
#define UART_CR_UTX_IR_INV_POS                                  (7U)
#define UART_CR_UTX_IR_INV_LEN                                  (1U)
#define UART_CR_UTX_IR_INV_MSK                                  (((1U<<UART_CR_UTX_IR_INV_LEN)-1)<<UART_CR_UTX_IR_INV_POS)
#define UART_CR_UTX_IR_INV_UMSK                                 (~(((1U<<UART_CR_UTX_IR_INV_LEN)-1)<<UART_CR_UTX_IR_INV_POS))
#define UART_CR_UTX_BIT_CNT_D                                   UART_CR_UTX_BIT_CNT_D
#define UART_CR_UTX_BIT_CNT_D_POS                               (8U)
#define UART_CR_UTX_BIT_CNT_D_LEN                               (3U)
#define UART_CR_UTX_BIT_CNT_D_MSK                               (((1U<<UART_CR_UTX_BIT_CNT_D_LEN)-1)<<UART_CR_UTX_BIT_CNT_D_POS)
#define UART_CR_UTX_BIT_CNT_D_UMSK                              (~(((1U<<UART_CR_UTX_BIT_CNT_D_LEN)-1)<<UART_CR_UTX_BIT_CNT_D_POS))
#define UART_CR_UTX_BIT_CNT_P                                   UART_CR_UTX_BIT_CNT_P
#define UART_CR_UTX_BIT_CNT_P_POS                               (11U)
#define UART_CR_UTX_BIT_CNT_P_LEN                               (2U)
#define UART_CR_UTX_BIT_CNT_P_MSK                               (((1U<<UART_CR_UTX_BIT_CNT_P_LEN)-1)<<UART_CR_UTX_BIT_CNT_P_POS)
#define UART_CR_UTX_BIT_CNT_P_UMSK                              (~(((1U<<UART_CR_UTX_BIT_CNT_P_LEN)-1)<<UART_CR_UTX_BIT_CNT_P_POS))
#define UART_CR_UTX_BIT_CNT_B                                   UART_CR_UTX_BIT_CNT_B
#define UART_CR_UTX_BIT_CNT_B_POS                               (13U)
#define UART_CR_UTX_BIT_CNT_B_LEN                               (3U)
#define UART_CR_UTX_BIT_CNT_B_MSK                               (((1U<<UART_CR_UTX_BIT_CNT_B_LEN)-1)<<UART_CR_UTX_BIT_CNT_B_POS)
#define UART_CR_UTX_BIT_CNT_B_UMSK                              (~(((1U<<UART_CR_UTX_BIT_CNT_B_LEN)-1)<<UART_CR_UTX_BIT_CNT_B_POS))
#define UART_CR_UTX_LEN                                         UART_CR_UTX_LEN
#define UART_CR_UTX_LEN_POS                                     (16U)
#define UART_CR_UTX_LEN_LEN                                     (16U)
#define UART_CR_UTX_LEN_MSK                                     (((1U<<UART_CR_UTX_LEN_LEN)-1)<<UART_CR_UTX_LEN_POS)
#define UART_CR_UTX_LEN_UMSK                                    (~(((1U<<UART_CR_UTX_LEN_LEN)-1)<<UART_CR_UTX_LEN_POS))

/* 0x4 : urx_config */
#define UART_URX_CONFIG_OFFSET                                  (0x4)
#define UART_CR_URX_EN                                          UART_CR_URX_EN
#define UART_CR_URX_EN_POS                                      (0U)
#define UART_CR_URX_EN_LEN                                      (1U)
#define UART_CR_URX_EN_MSK                                      (((1U<<UART_CR_URX_EN_LEN)-1)<<UART_CR_URX_EN_POS)
#define UART_CR_URX_EN_UMSK                                     (~(((1U<<UART_CR_URX_EN_LEN)-1)<<UART_CR_URX_EN_POS))
#define UART_CR_URX_ABR_EN                                      UART_CR_URX_ABR_EN
#define UART_CR_URX_ABR_EN_POS                                  (1U)
#define UART_CR_URX_ABR_EN_LEN                                  (1U)
#define UART_CR_URX_ABR_EN_MSK                                  (((1U<<UART_CR_URX_ABR_EN_LEN)-1)<<UART_CR_URX_ABR_EN_POS)
#define UART_CR_URX_ABR_EN_UMSK                                 (~(((1U<<UART_CR_URX_ABR_EN_LEN)-1)<<UART_CR_URX_ABR_EN_POS))
#define UART_CR_URX_LIN_EN                                      UART_CR_URX_LIN_EN
#define UART_CR_URX_LIN_EN_POS                                  (3U)
#define UART_CR_URX_LIN_EN_LEN                                  (1U)
#define UART_CR_URX_LIN_EN_MSK                                  (((1U<<UART_CR_URX_LIN_EN_LEN)-1)<<UART_CR_URX_LIN_EN_POS)
#define UART_CR_URX_LIN_EN_UMSK                                 (~(((1U<<UART_CR_URX_LIN_EN_LEN)-1)<<UART_CR_URX_LIN_EN_POS))
#define UART_CR_URX_PRT_EN                                      UART_CR_URX_PRT_EN
#define UART_CR_URX_PRT_EN_POS                                  (4U)
#define UART_CR_URX_PRT_EN_LEN                                  (1U)
#define UART_CR_URX_PRT_EN_MSK                                  (((1U<<UART_CR_URX_PRT_EN_LEN)-1)<<UART_CR_URX_PRT_EN_POS)
#define UART_CR_URX_PRT_EN_UMSK                                 (~(((1U<<UART_CR_URX_PRT_EN_LEN)-1)<<UART_CR_URX_PRT_EN_POS))
#define UART_CR_URX_PRT_SEL                                     UART_CR_URX_PRT_SEL
#define UART_CR_URX_PRT_SEL_POS                                 (5U)
#define UART_CR_URX_PRT_SEL_LEN                                 (1U)
#define UART_CR_URX_PRT_SEL_MSK                                 (((1U<<UART_CR_URX_PRT_SEL_LEN)-1)<<UART_CR_URX_PRT_SEL_POS)
#define UART_CR_URX_PRT_SEL_UMSK                                (~(((1U<<UART_CR_URX_PRT_SEL_LEN)-1)<<UART_CR_URX_PRT_SEL_POS))
#define UART_CR_URX_IR_EN                                       UART_CR_URX_IR_EN
#define UART_CR_URX_IR_EN_POS                                   (6U)
#define UART_CR_URX_IR_EN_LEN                                   (1U)
#define UART_CR_URX_IR_EN_MSK                                   (((1U<<UART_CR_URX_IR_EN_LEN)-1)<<UART_CR_URX_IR_EN_POS)
#define UART_CR_URX_IR_EN_UMSK                                  (~(((1U<<UART_CR_URX_IR_EN_LEN)-1)<<UART_CR_URX_IR_EN_POS))
#define UART_CR_URX_IR_INV                                      UART_CR_URX_IR_INV
#define UART_CR_URX_IR_INV_POS                                  (7U)
#define UART_CR_URX_IR_INV_LEN                                  (1U)
#define UART_CR_URX_IR_INV_MSK                                  (((1U<<UART_CR_URX_IR_INV_LEN)-1)<<UART_CR_URX_IR_INV_POS)
#define UART_CR_URX_IR_INV_UMSK                                 (~(((1U<<UART_CR_URX_IR_INV_LEN)-1)<<UART_CR_URX_IR_INV_POS))
#define UART_CR_URX_BIT_CNT_D                                   UART_CR_URX_BIT_CNT_D
#define UART_CR_URX_BIT_CNT_D_POS                               (8U)
#define UART_CR_URX_BIT_CNT_D_LEN                               (3U)
#define UART_CR_URX_BIT_CNT_D_MSK                               (((1U<<UART_CR_URX_BIT_CNT_D_LEN)-1)<<UART_CR_URX_BIT_CNT_D_POS)
#define UART_CR_URX_BIT_CNT_D_UMSK                              (~(((1U<<UART_CR_URX_BIT_CNT_D_LEN)-1)<<UART_CR_URX_BIT_CNT_D_POS))
#define UART_CR_URX_DEG_EN                                      UART_CR_URX_DEG_EN
#define UART_CR_URX_DEG_EN_POS                                  (11U)
#define UART_CR_URX_DEG_EN_LEN                                  (1U)
#define UART_CR_URX_DEG_EN_MSK                                  (((1U<<UART_CR_URX_DEG_EN_LEN)-1)<<UART_CR_URX_DEG_EN_POS)
#define UART_CR_URX_DEG_EN_UMSK                                 (~(((1U<<UART_CR_URX_DEG_EN_LEN)-1)<<UART_CR_URX_DEG_EN_POS))
#define UART_CR_URX_DEG_CNT                                     UART_CR_URX_DEG_CNT
#define UART_CR_URX_DEG_CNT_POS                                 (12U)
#define UART_CR_URX_DEG_CNT_LEN                                 (4U)
#define UART_CR_URX_DEG_CNT_MSK                                 (((1U<<UART_CR_URX_DEG_CNT_LEN)-1)<<UART_CR_URX_DEG_CNT_POS)
#define UART_CR_URX_DEG_CNT_UMSK                                (~(((1U<<UART_CR_URX_DEG_CNT_LEN)-1)<<UART_CR_URX_DEG_CNT_POS))
#define UART_CR_URX_LEN                                         UART_CR_URX_LEN
#define UART_CR_URX_LEN_POS                                     (16U)
#define UART_CR_URX_LEN_LEN                                     (16U)
#define UART_CR_URX_LEN_MSK                                     (((1U<<UART_CR_URX_LEN_LEN)-1)<<UART_CR_URX_LEN_POS)
#define UART_CR_URX_LEN_UMSK                                    (~(((1U<<UART_CR_URX_LEN_LEN)-1)<<UART_CR_URX_LEN_POS))

/* 0x8 : uart_bit_prd */
#define UART_BIT_PRD_OFFSET                                     (0x8)
#define UART_CR_UTX_BIT_PRD                                     UART_CR_UTX_BIT_PRD
#define UART_CR_UTX_BIT_PRD_POS                                 (0U)
#define UART_CR_UTX_BIT_PRD_LEN                                 (16U)
#define UART_CR_UTX_BIT_PRD_MSK                                 (((1U<<UART_CR_UTX_BIT_PRD_LEN)-1)<<UART_CR_UTX_BIT_PRD_POS)
#define UART_CR_UTX_BIT_PRD_UMSK                                (~(((1U<<UART_CR_UTX_BIT_PRD_LEN)-1)<<UART_CR_UTX_BIT_PRD_POS))
#define UART_CR_URX_BIT_PRD                                     UART_CR_URX_BIT_PRD
#define UART_CR_URX_BIT_PRD_POS                                 (16U)
#define UART_CR_URX_BIT_PRD_LEN                                 (16U)
#define UART_CR_URX_BIT_PRD_MSK                                 (((1U<<UART_CR_URX_BIT_PRD_LEN)-1)<<UART_CR_URX_BIT_PRD_POS)
#define UART_CR_URX_BIT_PRD_UMSK                                (~(((1U<<UART_CR_URX_BIT_PRD_LEN)-1)<<UART_CR_URX_BIT_PRD_POS))

/* 0xC : data_config */
#define UART_DATA_CONFIG_OFFSET                                 (0xC)
#define UART_CR_UART_BIT_INV                                    UART_CR_UART_BIT_INV
#define UART_CR_UART_BIT_INV_POS                                (0U)
#define UART_CR_UART_BIT_INV_LEN                                (1U)
#define UART_CR_UART_BIT_INV_MSK                                (((1U<<UART_CR_UART_BIT_INV_LEN)-1)<<UART_CR_UART_BIT_INV_POS)
#define UART_CR_UART_BIT_INV_UMSK                               (~(((1U<<UART_CR_UART_BIT_INV_LEN)-1)<<UART_CR_UART_BIT_INV_POS))

/* 0x10 : utx_ir_position */
#define UART_UTX_IR_POSITION_OFFSET                             (0x10)
#define UART_CR_UTX_IR_POS_S                                    UART_CR_UTX_IR_POS_S
#define UART_CR_UTX_IR_POS_S_POS                                (0U)
#define UART_CR_UTX_IR_POS_S_LEN                                (16U)
#define UART_CR_UTX_IR_POS_S_MSK                                (((1U<<UART_CR_UTX_IR_POS_S_LEN)-1)<<UART_CR_UTX_IR_POS_S_POS)
#define UART_CR_UTX_IR_POS_S_UMSK                               (~(((1U<<UART_CR_UTX_IR_POS_S_LEN)-1)<<UART_CR_UTX_IR_POS_S_POS))
#define UART_CR_UTX_IR_POS_P                                    UART_CR_UTX_IR_POS_P
#define UART_CR_UTX_IR_POS_P_POS                                (16U)
#define UART_CR_UTX_IR_POS_P_LEN                                (16U)
#define UART_CR_UTX_IR_POS_P_MSK                                (((1U<<UART_CR_UTX_IR_POS_P_LEN)-1)<<UART_CR_UTX_IR_POS_P_POS)
#define UART_CR_UTX_IR_POS_P_UMSK                               (~(((1U<<UART_CR_UTX_IR_POS_P_LEN)-1)<<UART_CR_UTX_IR_POS_P_POS))

/* 0x14 : urx_ir_position */
#define UART_URX_IR_POSITION_OFFSET                             (0x14)
#define UART_CR_URX_IR_POS_S                                    UART_CR_URX_IR_POS_S
#define UART_CR_URX_IR_POS_S_POS                                (0U)
#define UART_CR_URX_IR_POS_S_LEN                                (16U)
#define UART_CR_URX_IR_POS_S_MSK                                (((1U<<UART_CR_URX_IR_POS_S_LEN)-1)<<UART_CR_URX_IR_POS_S_POS)
#define UART_CR_URX_IR_POS_S_UMSK                               (~(((1U<<UART_CR_URX_IR_POS_S_LEN)-1)<<UART_CR_URX_IR_POS_S_POS))

/* 0x18 : urx_rto_timer */
#define UART_URX_RTO_TIMER_OFFSET                               (0x18)
#define UART_CR_URX_RTO_VALUE                                   UART_CR_URX_RTO_VALUE
#define UART_CR_URX_RTO_VALUE_POS                               (0U)
#define UART_CR_URX_RTO_VALUE_LEN                               (8U)
#define UART_CR_URX_RTO_VALUE_MSK                               (((1U<<UART_CR_URX_RTO_VALUE_LEN)-1)<<UART_CR_URX_RTO_VALUE_POS)
#define UART_CR_URX_RTO_VALUE_UMSK                              (~(((1U<<UART_CR_URX_RTO_VALUE_LEN)-1)<<UART_CR_URX_RTO_VALUE_POS))

/* 0x1C : uart_sw_mode */
#define UART_SW_MODE_OFFSET                                     (0x1C)
#define UART_CR_UTX_TXD_SW_MODE                                 UART_CR_UTX_TXD_SW_MODE
#define UART_CR_UTX_TXD_SW_MODE_POS                             (0U)
#define UART_CR_UTX_TXD_SW_MODE_LEN                             (1U)
#define UART_CR_UTX_TXD_SW_MODE_MSK                             (((1U<<UART_CR_UTX_TXD_SW_MODE_LEN)-1)<<UART_CR_UTX_TXD_SW_MODE_POS)
#define UART_CR_UTX_TXD_SW_MODE_UMSK                            (~(((1U<<UART_CR_UTX_TXD_SW_MODE_LEN)-1)<<UART_CR_UTX_TXD_SW_MODE_POS))
#define UART_CR_UTX_TXD_SW_VAL                                  UART_CR_UTX_TXD_SW_VAL
#define UART_CR_UTX_TXD_SW_VAL_POS                              (1U)
#define UART_CR_UTX_TXD_SW_VAL_LEN                              (1U)
#define UART_CR_UTX_TXD_SW_VAL_MSK                              (((1U<<UART_CR_UTX_TXD_SW_VAL_LEN)-1)<<UART_CR_UTX_TXD_SW_VAL_POS)
#define UART_CR_UTX_TXD_SW_VAL_UMSK                             (~(((1U<<UART_CR_UTX_TXD_SW_VAL_LEN)-1)<<UART_CR_UTX_TXD_SW_VAL_POS))
#define UART_CR_URX_RTS_SW_MODE                                 UART_CR_URX_RTS_SW_MODE
#define UART_CR_URX_RTS_SW_MODE_POS                             (2U)
#define UART_CR_URX_RTS_SW_MODE_LEN                             (1U)
#define UART_CR_URX_RTS_SW_MODE_MSK                             (((1U<<UART_CR_URX_RTS_SW_MODE_LEN)-1)<<UART_CR_URX_RTS_SW_MODE_POS)
#define UART_CR_URX_RTS_SW_MODE_UMSK                            (~(((1U<<UART_CR_URX_RTS_SW_MODE_LEN)-1)<<UART_CR_URX_RTS_SW_MODE_POS))
#define UART_CR_URX_RTS_SW_VAL                                  UART_CR_URX_RTS_SW_VAL
#define UART_CR_URX_RTS_SW_VAL_POS                              (3U)
#define UART_CR_URX_RTS_SW_VAL_LEN                              (1U)
#define UART_CR_URX_RTS_SW_VAL_MSK                              (((1U<<UART_CR_URX_RTS_SW_VAL_LEN)-1)<<UART_CR_URX_RTS_SW_VAL_POS)
#define UART_CR_URX_RTS_SW_VAL_UMSK                             (~(((1U<<UART_CR_URX_RTS_SW_VAL_LEN)-1)<<UART_CR_URX_RTS_SW_VAL_POS))

/* 0x20 : UART interrupt status */
#define UART_INT_STS_OFFSET                                     (0x20)
#define UART_UTX_END_INT                                        UART_UTX_END_INT
#define UART_UTX_END_INT_POS                                    (0U)
#define UART_UTX_END_INT_LEN                                    (1U)
#define UART_UTX_END_INT_MSK                                    (((1U<<UART_UTX_END_INT_LEN)-1)<<UART_UTX_END_INT_POS)
#define UART_UTX_END_INT_UMSK                                   (~(((1U<<UART_UTX_END_INT_LEN)-1)<<UART_UTX_END_INT_POS))
#define UART_URX_END_INT                                        UART_URX_END_INT
#define UART_URX_END_INT_POS                                    (1U)
#define UART_URX_END_INT_LEN                                    (1U)
#define UART_URX_END_INT_MSK                                    (((1U<<UART_URX_END_INT_LEN)-1)<<UART_URX_END_INT_POS)
#define UART_URX_END_INT_UMSK                                   (~(((1U<<UART_URX_END_INT_LEN)-1)<<UART_URX_END_INT_POS))
#define UART_UTX_FIFO_INT                                       UART_UTX_FIFO_INT
#define UART_UTX_FIFO_INT_POS                                   (2U)
#define UART_UTX_FIFO_INT_LEN                                   (1U)
#define UART_UTX_FIFO_INT_MSK                                   (((1U<<UART_UTX_FIFO_INT_LEN)-1)<<UART_UTX_FIFO_INT_POS)
#define UART_UTX_FIFO_INT_UMSK                                  (~(((1U<<UART_UTX_FIFO_INT_LEN)-1)<<UART_UTX_FIFO_INT_POS))
#define UART_URX_FIFO_INT                                       UART_URX_FIFO_INT
#define UART_URX_FIFO_INT_POS                                   (3U)
#define UART_URX_FIFO_INT_LEN                                   (1U)
#define UART_URX_FIFO_INT_MSK                                   (((1U<<UART_URX_FIFO_INT_LEN)-1)<<UART_URX_FIFO_INT_POS)
#define UART_URX_FIFO_INT_UMSK                                  (~(((1U<<UART_URX_FIFO_INT_LEN)-1)<<UART_URX_FIFO_INT_POS))
#define UART_URX_RTO_INT                                        UART_URX_RTO_INT
#define UART_URX_RTO_INT_POS                                    (4U)
#define UART_URX_RTO_INT_LEN                                    (1U)
#define UART_URX_RTO_INT_MSK                                    (((1U<<UART_URX_RTO_INT_LEN)-1)<<UART_URX_RTO_INT_POS)
#define UART_URX_RTO_INT_UMSK                                   (~(((1U<<UART_URX_RTO_INT_LEN)-1)<<UART_URX_RTO_INT_POS))
#define UART_URX_PCE_INT                                        UART_URX_PCE_INT
#define UART_URX_PCE_INT_POS                                    (5U)
#define UART_URX_PCE_INT_LEN                                    (1U)
#define UART_URX_PCE_INT_MSK                                    (((1U<<UART_URX_PCE_INT_LEN)-1)<<UART_URX_PCE_INT_POS)
#define UART_URX_PCE_INT_UMSK                                   (~(((1U<<UART_URX_PCE_INT_LEN)-1)<<UART_URX_PCE_INT_POS))
#define UART_UTX_FER_INT                                        UART_UTX_FER_INT
#define UART_UTX_FER_INT_POS                                    (6U)
#define UART_UTX_FER_INT_LEN                                    (1U)
#define UART_UTX_FER_INT_MSK                                    (((1U<<UART_UTX_FER_INT_LEN)-1)<<UART_UTX_FER_INT_POS)
#define UART_UTX_FER_INT_UMSK                                   (~(((1U<<UART_UTX_FER_INT_LEN)-1)<<UART_UTX_FER_INT_POS))
#define UART_URX_FER_INT                                        UART_URX_FER_INT
#define UART_URX_FER_INT_POS                                    (7U)
#define UART_URX_FER_INT_LEN                                    (1U)
#define UART_URX_FER_INT_MSK                                    (((1U<<UART_URX_FER_INT_LEN)-1)<<UART_URX_FER_INT_POS)
#define UART_URX_FER_INT_UMSK                                   (~(((1U<<UART_URX_FER_INT_LEN)-1)<<UART_URX_FER_INT_POS))
#define UART_URX_LSE_INT                                        UART_URX_LSE_INT
#define UART_URX_LSE_INT_POS                                    (8U)
#define UART_URX_LSE_INT_LEN                                    (1U)
#define UART_URX_LSE_INT_MSK                                    (((1U<<UART_URX_LSE_INT_LEN)-1)<<UART_URX_LSE_INT_POS)
#define UART_URX_LSE_INT_UMSK                                   (~(((1U<<UART_URX_LSE_INT_LEN)-1)<<UART_URX_LSE_INT_POS))
#define UART_URX_BCR_INT                                        UART_URX_BCR_INT
#define UART_URX_BCR_INT_POS                                    (9U)
#define UART_URX_BCR_INT_LEN                                    (1U)
#define UART_URX_BCR_INT_MSK                                    (((1U<<UART_URX_BCR_INT_LEN)-1)<<UART_URX_BCR_INT_POS)
#define UART_URX_BCR_INT_UMSK                                   (~(((1U<<UART_URX_BCR_INT_LEN)-1)<<UART_URX_BCR_INT_POS))
#define UART_URX_ADS_INT                                        UART_URX_ADS_INT
#define UART_URX_ADS_INT_POS                                    (10U)
#define UART_URX_ADS_INT_LEN                                    (1U)
#define UART_URX_ADS_INT_MSK                                    (((1U<<UART_URX_ADS_INT_LEN)-1)<<UART_URX_ADS_INT_POS)
#define UART_URX_ADS_INT_UMSK                                   (~(((1U<<UART_URX_ADS_INT_LEN)-1)<<UART_URX_ADS_INT_POS))
#define UART_URX_AD5_INT                                        UART_URX_AD5_INT
#define UART_URX_AD5_INT_POS                                    (11U)
#define UART_URX_AD5_INT_LEN                                    (1U)
#define UART_URX_AD5_INT_MSK                                    (((1U<<UART_URX_AD5_INT_LEN)-1)<<UART_URX_AD5_INT_POS)
#define UART_URX_AD5_INT_UMSK                                   (~(((1U<<UART_URX_AD5_INT_LEN)-1)<<UART_URX_AD5_INT_POS))

/* 0x24 : UART interrupt mask */
#define UART_INT_MASK_OFFSET                                    (0x24)
#define UART_CR_UTX_END_MASK                                    UART_CR_UTX_END_MASK
#define UART_CR_UTX_END_MASK_POS                                (0U)
#define UART_CR_UTX_END_MASK_LEN                                (1U)
#define UART_CR_UTX_END_MASK_MSK                                (((1U<<UART_CR_UTX_END_MASK_LEN)-1)<<UART_CR_UTX_END_MASK_POS)
#define UART_CR_UTX_END_MASK_UMSK                               (~(((1U<<UART_CR_UTX_END_MASK_LEN)-1)<<UART_CR_UTX_END_MASK_POS))
#define UART_CR_URX_END_MASK                                    UART_CR_URX_END_MASK
#define UART_CR_URX_END_MASK_POS                                (1U)
#define UART_CR_URX_END_MASK_LEN                                (1U)
#define UART_CR_URX_END_MASK_MSK                                (((1U<<UART_CR_URX_END_MASK_LEN)-1)<<UART_CR_URX_END_MASK_POS)
#define UART_CR_URX_END_MASK_UMSK                               (~(((1U<<UART_CR_URX_END_MASK_LEN)-1)<<UART_CR_URX_END_MASK_POS))
#define UART_CR_UTX_FIFO_MASK                                   UART_CR_UTX_FIFO_MASK
#define UART_CR_UTX_FIFO_MASK_POS                               (2U)
#define UART_CR_UTX_FIFO_MASK_LEN                               (1U)
#define UART_CR_UTX_FIFO_MASK_MSK                               (((1U<<UART_CR_UTX_FIFO_MASK_LEN)-1)<<UART_CR_UTX_FIFO_MASK_POS)
#define UART_CR_UTX_FIFO_MASK_UMSK                              (~(((1U<<UART_CR_UTX_FIFO_MASK_LEN)-1)<<UART_CR_UTX_FIFO_MASK_POS))
#define UART_CR_URX_FIFO_MASK                                   UART_CR_URX_FIFO_MASK
#define UART_CR_URX_FIFO_MASK_POS                               (3U)
#define UART_CR_URX_FIFO_MASK_LEN                               (1U)
#define UART_CR_URX_FIFO_MASK_MSK                               (((1U<<UART_CR_URX_FIFO_MASK_LEN)-1)<<UART_CR_URX_FIFO_MASK_POS)
#define UART_CR_URX_FIFO_MASK_UMSK                              (~(((1U<<UART_CR_URX_FIFO_MASK_LEN)-1)<<UART_CR_URX_FIFO_MASK_POS))
#define UART_CR_URX_RTO_MASK                                    UART_CR_URX_RTO_MASK
#define UART_CR_URX_RTO_MASK_POS                                (4U)
#define UART_CR_URX_RTO_MASK_LEN                                (1U)
#define UART_CR_URX_RTO_MASK_MSK                                (((1U<<UART_CR_URX_RTO_MASK_LEN)-1)<<UART_CR_URX_RTO_MASK_POS)
#define UART_CR_URX_RTO_MASK_UMSK                               (~(((1U<<UART_CR_URX_RTO_MASK_LEN)-1)<<UART_CR_URX_RTO_MASK_POS))
#define UART_CR_URX_PCE_MASK                                    UART_CR_URX_PCE_MASK
#define UART_CR_URX_PCE_MASK_POS                                (5U)
#define UART_CR_URX_PCE_MASK_LEN                                (1U)
#define UART_CR_URX_PCE_MASK_MSK                                (((1U<<UART_CR_URX_PCE_MASK_LEN)-1)<<UART_CR_URX_PCE_MASK_POS)
#define UART_CR_URX_PCE_MASK_UMSK                               (~(((1U<<UART_CR_URX_PCE_MASK_LEN)-1)<<UART_CR_URX_PCE_MASK_POS))
#define UART_CR_UTX_FER_MASK                                    UART_CR_UTX_FER_MASK
#define UART_CR_UTX_FER_MASK_POS                                (6U)
#define UART_CR_UTX_FER_MASK_LEN                                (1U)
#define UART_CR_UTX_FER_MASK_MSK                                (((1U<<UART_CR_UTX_FER_MASK_LEN)-1)<<UART_CR_UTX_FER_MASK_POS)
#define UART_CR_UTX_FER_MASK_UMSK                               (~(((1U<<UART_CR_UTX_FER_MASK_LEN)-1)<<UART_CR_UTX_FER_MASK_POS))
#define UART_CR_URX_FER_MASK                                    UART_CR_URX_FER_MASK
#define UART_CR_URX_FER_MASK_POS                                (7U)
#define UART_CR_URX_FER_MASK_LEN                                (1U)
#define UART_CR_URX_FER_MASK_MSK                                (((1U<<UART_CR_URX_FER_MASK_LEN)-1)<<UART_CR_URX_FER_MASK_POS)
#define UART_CR_URX_FER_MASK_UMSK                               (~(((1U<<UART_CR_URX_FER_MASK_LEN)-1)<<UART_CR_URX_FER_MASK_POS))
#define UART_CR_URX_LSE_MASK                                    UART_CR_URX_LSE_MASK
#define UART_CR_URX_LSE_MASK_POS                                (8U)
#define UART_CR_URX_LSE_MASK_LEN                                (1U)
#define UART_CR_URX_LSE_MASK_MSK                                (((1U<<UART_CR_URX_LSE_MASK_LEN)-1)<<UART_CR_URX_LSE_MASK_POS)
#define UART_CR_URX_LSE_MASK_UMSK                               (~(((1U<<UART_CR_URX_LSE_MASK_LEN)-1)<<UART_CR_URX_LSE_MASK_POS))
#define UART_CR_URX_BCR_MASK                                    UART_CR_URX_BCR_MASK
#define UART_CR_URX_BCR_MASK_POS                                (9U)
#define UART_CR_URX_BCR_MASK_LEN                                (1U)
#define UART_CR_URX_BCR_MASK_MSK                                (((1U<<UART_CR_URX_BCR_MASK_LEN)-1)<<UART_CR_URX_BCR_MASK_POS)
#define UART_CR_URX_BCR_MASK_UMSK                               (~(((1U<<UART_CR_URX_BCR_MASK_LEN)-1)<<UART_CR_URX_BCR_MASK_POS))
#define UART_CR_URX_ADS_MASK                                    UART_CR_URX_ADS_MASK
#define UART_CR_URX_ADS_MASK_POS                                (10U)
#define UART_CR_URX_ADS_MASK_LEN                                (1U)
#define UART_CR_URX_ADS_MASK_MSK                                (((1U<<UART_CR_URX_ADS_MASK_LEN)-1)<<UART_CR_URX_ADS_MASK_POS)
#define UART_CR_URX_ADS_MASK_UMSK                               (~(((1U<<UART_CR_URX_ADS_MASK_LEN)-1)<<UART_CR_URX_ADS_MASK_POS))
#define UART_CR_URX_AD5_MASK                                    UART_CR_URX_AD5_MASK
#define UART_CR_URX_AD5_MASK_POS                                (11U)
#define UART_CR_URX_AD5_MASK_LEN                                (1U)
#define UART_CR_URX_AD5_MASK_MSK                                (((1U<<UART_CR_URX_AD5_MASK_LEN)-1)<<UART_CR_URX_AD5_MASK_POS)
#define UART_CR_URX_AD5_MASK_UMSK                               (~(((1U<<UART_CR_URX_AD5_MASK_LEN)-1)<<UART_CR_URX_AD5_MASK_POS))

/* 0x28 : UART interrupt clear */
#define UART_INT_CLEAR_OFFSET                                   (0x28)
#define UART_CR_UTX_END_CLR                                     UART_CR_UTX_END_CLR
#define UART_CR_UTX_END_CLR_POS                                 (0U)
#define UART_CR_UTX_END_CLR_LEN                                 (1U)
#define UART_CR_UTX_END_CLR_MSK                                 (((1U<<UART_CR_UTX_END_CLR_LEN)-1)<<UART_CR_UTX_END_CLR_POS)
#define UART_CR_UTX_END_CLR_UMSK                                (~(((1U<<UART_CR_UTX_END_CLR_LEN)-1)<<UART_CR_UTX_END_CLR_POS))
#define UART_CR_URX_END_CLR                                     UART_CR_URX_END_CLR
#define UART_CR_URX_END_CLR_POS                                 (1U)
#define UART_CR_URX_END_CLR_LEN                                 (1U)
#define UART_CR_URX_END_CLR_MSK                                 (((1U<<UART_CR_URX_END_CLR_LEN)-1)<<UART_CR_URX_END_CLR_POS)
#define UART_CR_URX_END_CLR_UMSK                                (~(((1U<<UART_CR_URX_END_CLR_LEN)-1)<<UART_CR_URX_END_CLR_POS))
#define UART_CR_URX_RTO_CLR                                     UART_CR_URX_RTO_CLR
#define UART_CR_URX_RTO_CLR_POS                                 (4U)
#define UART_CR_URX_RTO_CLR_LEN                                 (1U)
#define UART_CR_URX_RTO_CLR_MSK                                 (((1U<<UART_CR_URX_RTO_CLR_LEN)-1)<<UART_CR_URX_RTO_CLR_POS)
#define UART_CR_URX_RTO_CLR_UMSK                                (~(((1U<<UART_CR_URX_RTO_CLR_LEN)-1)<<UART_CR_URX_RTO_CLR_POS))
#define UART_CR_URX_PCE_CLR                                     UART_CR_URX_PCE_CLR
#define UART_CR_URX_PCE_CLR_POS                                 (5U)
#define UART_CR_URX_PCE_CLR_LEN                                 (1U)
#define UART_CR_URX_PCE_CLR_MSK                                 (((1U<<UART_CR_URX_PCE_CLR_LEN)-1)<<UART_CR_URX_PCE_CLR_POS)
#define UART_CR_URX_PCE_CLR_UMSK                                (~(((1U<<UART_CR_URX_PCE_CLR_LEN)-1)<<UART_CR_URX_PCE_CLR_POS))
#define UART_CR_URX_LSE_CLR                                     UART_CR_URX_LSE_CLR
#define UART_CR_URX_LSE_CLR_POS                                 (8U)
#define UART_CR_URX_LSE_CLR_LEN                                 (1U)
#define UART_CR_URX_LSE_CLR_MSK                                 (((1U<<UART_CR_URX_LSE_CLR_LEN)-1)<<UART_CR_URX_LSE_CLR_POS)
#define UART_CR_URX_LSE_CLR_UMSK                                (~(((1U<<UART_CR_URX_LSE_CLR_LEN)-1)<<UART_CR_URX_LSE_CLR_POS))
#define UART_CR_URX_BCR_CLR                                     UART_CR_URX_BCR_CLR
#define UART_CR_URX_BCR_CLR_POS                                 (9U)
#define UART_CR_URX_BCR_CLR_LEN                                 (1U)
#define UART_CR_URX_BCR_CLR_MSK                                 (((1U<<UART_CR_URX_BCR_CLR_LEN)-1)<<UART_CR_URX_BCR_CLR_POS)
#define UART_CR_URX_BCR_CLR_UMSK                                (~(((1U<<UART_CR_URX_BCR_CLR_LEN)-1)<<UART_CR_URX_BCR_CLR_POS))
#define UART_CR_URX_ADS_CLR                                     UART_CR_URX_ADS_CLR
#define UART_CR_URX_ADS_CLR_POS                                 (10U)
#define UART_CR_URX_ADS_CLR_LEN                                 (1U)
#define UART_CR_URX_ADS_CLR_MSK                                 (((1U<<UART_CR_URX_ADS_CLR_LEN)-1)<<UART_CR_URX_ADS_CLR_POS)
#define UART_CR_URX_ADS_CLR_UMSK                                (~(((1U<<UART_CR_URX_ADS_CLR_LEN)-1)<<UART_CR_URX_ADS_CLR_POS))
#define UART_CR_URX_AD5_CLR                                     UART_CR_URX_AD5_CLR
#define UART_CR_URX_AD5_CLR_POS                                 (11U)
#define UART_CR_URX_AD5_CLR_LEN                                 (1U)
#define UART_CR_URX_AD5_CLR_MSK                                 (((1U<<UART_CR_URX_AD5_CLR_LEN)-1)<<UART_CR_URX_AD5_CLR_POS)
#define UART_CR_URX_AD5_CLR_UMSK                                (~(((1U<<UART_CR_URX_AD5_CLR_LEN)-1)<<UART_CR_URX_AD5_CLR_POS))

/* 0x2C : UART interrupt enable */
#define UART_INT_EN_OFFSET                                      (0x2C)
#define UART_CR_UTX_END_EN                                      UART_CR_UTX_END_EN
#define UART_CR_UTX_END_EN_POS                                  (0U)
#define UART_CR_UTX_END_EN_LEN                                  (1U)
#define UART_CR_UTX_END_EN_MSK                                  (((1U<<UART_CR_UTX_END_EN_LEN)-1)<<UART_CR_UTX_END_EN_POS)
#define UART_CR_UTX_END_EN_UMSK                                 (~(((1U<<UART_CR_UTX_END_EN_LEN)-1)<<UART_CR_UTX_END_EN_POS))
#define UART_CR_URX_END_EN                                      UART_CR_URX_END_EN
#define UART_CR_URX_END_EN_POS                                  (1U)
#define UART_CR_URX_END_EN_LEN                                  (1U)
#define UART_CR_URX_END_EN_MSK                                  (((1U<<UART_CR_URX_END_EN_LEN)-1)<<UART_CR_URX_END_EN_POS)
#define UART_CR_URX_END_EN_UMSK                                 (~(((1U<<UART_CR_URX_END_EN_LEN)-1)<<UART_CR_URX_END_EN_POS))
#define UART_CR_UTX_FIFO_EN                                     UART_CR_UTX_FIFO_EN
#define UART_CR_UTX_FIFO_EN_POS                                 (2U)
#define UART_CR_UTX_FIFO_EN_LEN                                 (1U)
#define UART_CR_UTX_FIFO_EN_MSK                                 (((1U<<UART_CR_UTX_FIFO_EN_LEN)-1)<<UART_CR_UTX_FIFO_EN_POS)
#define UART_CR_UTX_FIFO_EN_UMSK                                (~(((1U<<UART_CR_UTX_FIFO_EN_LEN)-1)<<UART_CR_UTX_FIFO_EN_POS))
#define UART_CR_URX_FIFO_EN                                     UART_CR_URX_FIFO_EN
#define UART_CR_URX_FIFO_EN_POS                                 (3U)
#define UART_CR_URX_FIFO_EN_LEN                                 (1U)
#define UART_CR_URX_FIFO_EN_MSK                                 (((1U<<UART_CR_URX_FIFO_EN_LEN)-1)<<UART_CR_URX_FIFO_EN_POS)
#define UART_CR_URX_FIFO_EN_UMSK                                (~(((1U<<UART_CR_URX_FIFO_EN_LEN)-1)<<UART_CR_URX_FIFO_EN_POS))
#define UART_CR_URX_RTO_EN                                      UART_CR_URX_RTO_EN
#define UART_CR_URX_RTO_EN_POS                                  (4U)
#define UART_CR_URX_RTO_EN_LEN                                  (1U)
#define UART_CR_URX_RTO_EN_MSK                                  (((1U<<UART_CR_URX_RTO_EN_LEN)-1)<<UART_CR_URX_RTO_EN_POS)
#define UART_CR_URX_RTO_EN_UMSK                                 (~(((1U<<UART_CR_URX_RTO_EN_LEN)-1)<<UART_CR_URX_RTO_EN_POS))
#define UART_CR_URX_PCE_EN                                      UART_CR_URX_PCE_EN
#define UART_CR_URX_PCE_EN_POS                                  (5U)
#define UART_CR_URX_PCE_EN_LEN                                  (1U)
#define UART_CR_URX_PCE_EN_MSK                                  (((1U<<UART_CR_URX_PCE_EN_LEN)-1)<<UART_CR_URX_PCE_EN_POS)
#define UART_CR_URX_PCE_EN_UMSK                                 (~(((1U<<UART_CR_URX_PCE_EN_LEN)-1)<<UART_CR_URX_PCE_EN_POS))
#define UART_CR_UTX_FER_EN                                      UART_CR_UTX_FER_EN
#define UART_CR_UTX_FER_EN_POS                                  (6U)
#define UART_CR_UTX_FER_EN_LEN                                  (1U)
#define UART_CR_UTX_FER_EN_MSK                                  (((1U<<UART_CR_UTX_FER_EN_LEN)-1)<<UART_CR_UTX_FER_EN_POS)
#define UART_CR_UTX_FER_EN_UMSK                                 (~(((1U<<UART_CR_UTX_FER_EN_LEN)-1)<<UART_CR_UTX_FER_EN_POS))
#define UART_CR_URX_FER_EN                                      UART_CR_URX_FER_EN
#define UART_CR_URX_FER_EN_POS                                  (7U)
#define UART_CR_URX_FER_EN_LEN                                  (1U)
#define UART_CR_URX_FER_EN_MSK                                  (((1U<<UART_CR_URX_FER_EN_LEN)-1)<<UART_CR_URX_FER_EN_POS)
#define UART_CR_URX_FER_EN_UMSK                                 (~(((1U<<UART_CR_URX_FER_EN_LEN)-1)<<UART_CR_URX_FER_EN_POS))
#define UART_CR_URX_LSE_EN                                      UART_CR_URX_LSE_EN
#define UART_CR_URX_LSE_EN_POS                                  (8U)
#define UART_CR_URX_LSE_EN_LEN                                  (1U)
#define UART_CR_URX_LSE_EN_MSK                                  (((1U<<UART_CR_URX_LSE_EN_LEN)-1)<<UART_CR_URX_LSE_EN_POS)
#define UART_CR_URX_LSE_EN_UMSK                                 (~(((1U<<UART_CR_URX_LSE_EN_LEN)-1)<<UART_CR_URX_LSE_EN_POS))
#define UART_CR_URX_BCR_EN                                      UART_CR_URX_BCR_EN
#define UART_CR_URX_BCR_EN_POS                                  (9U)
#define UART_CR_URX_BCR_EN_LEN                                  (1U)
#define UART_CR_URX_BCR_EN_MSK                                  (((1U<<UART_CR_URX_BCR_EN_LEN)-1)<<UART_CR_URX_BCR_EN_POS)
#define UART_CR_URX_BCR_EN_UMSK                                 (~(((1U<<UART_CR_URX_BCR_EN_LEN)-1)<<UART_CR_URX_BCR_EN_POS))
#define UART_CR_URX_ADS_EN                                      UART_CR_URX_ADS_EN
#define UART_CR_URX_ADS_EN_POS                                  (10U)
#define UART_CR_URX_ADS_EN_LEN                                  (1U)
#define UART_CR_URX_ADS_EN_MSK                                  (((1U<<UART_CR_URX_ADS_EN_LEN)-1)<<UART_CR_URX_ADS_EN_POS)
#define UART_CR_URX_ADS_EN_UMSK                                 (~(((1U<<UART_CR_URX_ADS_EN_LEN)-1)<<UART_CR_URX_ADS_EN_POS))
#define UART_CR_URX_AD5_EN                                      UART_CR_URX_AD5_EN
#define UART_CR_URX_AD5_EN_POS                                  (11U)
#define UART_CR_URX_AD5_EN_LEN                                  (1U)
#define UART_CR_URX_AD5_EN_MSK                                  (((1U<<UART_CR_URX_AD5_EN_LEN)-1)<<UART_CR_URX_AD5_EN_POS)
#define UART_CR_URX_AD5_EN_UMSK                                 (~(((1U<<UART_CR_URX_AD5_EN_LEN)-1)<<UART_CR_URX_AD5_EN_POS))

/* 0x30 : uart_status */
#define UART_STATUS_OFFSET                                      (0x30)
#define UART_STS_UTX_BUS_BUSY                                   UART_STS_UTX_BUS_BUSY
#define UART_STS_UTX_BUS_BUSY_POS                               (0U)
#define UART_STS_UTX_BUS_BUSY_LEN                               (1U)
#define UART_STS_UTX_BUS_BUSY_MSK                               (((1U<<UART_STS_UTX_BUS_BUSY_LEN)-1)<<UART_STS_UTX_BUS_BUSY_POS)
#define UART_STS_UTX_BUS_BUSY_UMSK                              (~(((1U<<UART_STS_UTX_BUS_BUSY_LEN)-1)<<UART_STS_UTX_BUS_BUSY_POS))
#define UART_STS_URX_BUS_BUSY                                   UART_STS_URX_BUS_BUSY
#define UART_STS_URX_BUS_BUSY_POS                               (1U)
#define UART_STS_URX_BUS_BUSY_LEN                               (1U)
#define UART_STS_URX_BUS_BUSY_MSK                               (((1U<<UART_STS_URX_BUS_BUSY_LEN)-1)<<UART_STS_URX_BUS_BUSY_POS)
#define UART_STS_URX_BUS_BUSY_UMSK                              (~(((1U<<UART_STS_URX_BUS_BUSY_LEN)-1)<<UART_STS_URX_BUS_BUSY_POS))

/* 0x34 : sts_urx_abr_prd */
#define UART_STS_URX_ABR_PRD_OFFSET                             (0x34)
#define UART_STS_URX_ABR_PRD_START                              UART_STS_URX_ABR_PRD_START
#define UART_STS_URX_ABR_PRD_START_POS                          (0U)
#define UART_STS_URX_ABR_PRD_START_LEN                          (16U)
#define UART_STS_URX_ABR_PRD_START_MSK                          (((1U<<UART_STS_URX_ABR_PRD_START_LEN)-1)<<UART_STS_URX_ABR_PRD_START_POS)
#define UART_STS_URX_ABR_PRD_START_UMSK                         (~(((1U<<UART_STS_URX_ABR_PRD_START_LEN)-1)<<UART_STS_URX_ABR_PRD_START_POS))
#define UART_STS_URX_ABR_PRD_0X55                               UART_STS_URX_ABR_PRD_0X55
#define UART_STS_URX_ABR_PRD_0X55_POS                           (16U)
#define UART_STS_URX_ABR_PRD_0X55_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_0X55_MSK                           (((1U<<UART_STS_URX_ABR_PRD_0X55_LEN)-1)<<UART_STS_URX_ABR_PRD_0X55_POS)
#define UART_STS_URX_ABR_PRD_0X55_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_0X55_LEN)-1)<<UART_STS_URX_ABR_PRD_0X55_POS))

/* 0x38 : urx_abr_prd_b01 */
#define UART_URX_ABR_PRD_B01_OFFSET                             (0x38)
#define UART_STS_URX_ABR_PRD_BIT0                               UART_STS_URX_ABR_PRD_BIT0
#define UART_STS_URX_ABR_PRD_BIT0_POS                           (0U)
#define UART_STS_URX_ABR_PRD_BIT0_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT0_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT0_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT0_POS)
#define UART_STS_URX_ABR_PRD_BIT0_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT0_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT0_POS))
#define UART_STS_URX_ABR_PRD_BIT1                               UART_STS_URX_ABR_PRD_BIT1
#define UART_STS_URX_ABR_PRD_BIT1_POS                           (16U)
#define UART_STS_URX_ABR_PRD_BIT1_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT1_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT1_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT1_POS)
#define UART_STS_URX_ABR_PRD_BIT1_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT1_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT1_POS))

/* 0x3C : urx_abr_prd_b23 */
#define UART_URX_ABR_PRD_B23_OFFSET                             (0x3C)
#define UART_STS_URX_ABR_PRD_BIT2                               UART_STS_URX_ABR_PRD_BIT2
#define UART_STS_URX_ABR_PRD_BIT2_POS                           (0U)
#define UART_STS_URX_ABR_PRD_BIT2_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT2_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT2_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT2_POS)
#define UART_STS_URX_ABR_PRD_BIT2_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT2_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT2_POS))
#define UART_STS_URX_ABR_PRD_BIT3                               UART_STS_URX_ABR_PRD_BIT3
#define UART_STS_URX_ABR_PRD_BIT3_POS                           (16U)
#define UART_STS_URX_ABR_PRD_BIT3_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT3_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT3_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT3_POS)
#define UART_STS_URX_ABR_PRD_BIT3_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT3_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT3_POS))

/* 0x40 : urx_abr_prd_b45 */
#define UART_URX_ABR_PRD_B45_OFFSET                             (0x40)
#define UART_STS_URX_ABR_PRD_BIT4                               UART_STS_URX_ABR_PRD_BIT4
#define UART_STS_URX_ABR_PRD_BIT4_POS                           (0U)
#define UART_STS_URX_ABR_PRD_BIT4_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT4_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT4_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT4_POS)
#define UART_STS_URX_ABR_PRD_BIT4_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT4_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT4_POS))
#define UART_STS_URX_ABR_PRD_BIT5                               UART_STS_URX_ABR_PRD_BIT5
#define UART_STS_URX_ABR_PRD_BIT5_POS                           (16U)
#define UART_STS_URX_ABR_PRD_BIT5_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT5_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT5_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT5_POS)
#define UART_STS_URX_ABR_PRD_BIT5_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT5_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT5_POS))

/* 0x44 : urx_abr_prd_b67 */
#define UART_URX_ABR_PRD_B67_OFFSET                             (0x44)
#define UART_STS_URX_ABR_PRD_BIT6                               UART_STS_URX_ABR_PRD_BIT6
#define UART_STS_URX_ABR_PRD_BIT6_POS                           (0U)
#define UART_STS_URX_ABR_PRD_BIT6_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT6_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT6_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT6_POS)
#define UART_STS_URX_ABR_PRD_BIT6_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT6_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT6_POS))
#define UART_STS_URX_ABR_PRD_BIT7                               UART_STS_URX_ABR_PRD_BIT7
#define UART_STS_URX_ABR_PRD_BIT7_POS                           (16U)
#define UART_STS_URX_ABR_PRD_BIT7_LEN                           (16U)
#define UART_STS_URX_ABR_PRD_BIT7_MSK                           (((1U<<UART_STS_URX_ABR_PRD_BIT7_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT7_POS)
#define UART_STS_URX_ABR_PRD_BIT7_UMSK                          (~(((1U<<UART_STS_URX_ABR_PRD_BIT7_LEN)-1)<<UART_STS_URX_ABR_PRD_BIT7_POS))

/* 0x48 : urx_abr_pw_tol */
#define UART_URX_ABR_PW_TOL_OFFSET                              (0x48)
#define UART_CR_URX_ABR_PW_TOL                                  UART_CR_URX_ABR_PW_TOL
#define UART_CR_URX_ABR_PW_TOL_POS                              (0U)
#define UART_CR_URX_ABR_PW_TOL_LEN                              (8U)
#define UART_CR_URX_ABR_PW_TOL_MSK                              (((1U<<UART_CR_URX_ABR_PW_TOL_LEN)-1)<<UART_CR_URX_ABR_PW_TOL_POS)
#define UART_CR_URX_ABR_PW_TOL_UMSK                             (~(((1U<<UART_CR_URX_ABR_PW_TOL_LEN)-1)<<UART_CR_URX_ABR_PW_TOL_POS))

/* 0x50 : urx_bcr_int_cfg */
#define UART_URX_BCR_INT_CFG_OFFSET                             (0x50)
#define UART_CR_URX_BCR_VALUE                                   UART_CR_URX_BCR_VALUE
#define UART_CR_URX_BCR_VALUE_POS                               (0U)
#define UART_CR_URX_BCR_VALUE_LEN                               (16U)
#define UART_CR_URX_BCR_VALUE_MSK                               (((1U<<UART_CR_URX_BCR_VALUE_LEN)-1)<<UART_CR_URX_BCR_VALUE_POS)
#define UART_CR_URX_BCR_VALUE_UMSK                              (~(((1U<<UART_CR_URX_BCR_VALUE_LEN)-1)<<UART_CR_URX_BCR_VALUE_POS))
#define UART_STS_URX_BCR_COUNT                                  UART_STS_URX_BCR_COUNT
#define UART_STS_URX_BCR_COUNT_POS                              (16U)
#define UART_STS_URX_BCR_COUNT_LEN                              (16U)
#define UART_STS_URX_BCR_COUNT_MSK                              (((1U<<UART_STS_URX_BCR_COUNT_LEN)-1)<<UART_STS_URX_BCR_COUNT_POS)
#define UART_STS_URX_BCR_COUNT_UMSK                             (~(((1U<<UART_STS_URX_BCR_COUNT_LEN)-1)<<UART_STS_URX_BCR_COUNT_POS))

/* 0x54 : utx_rs485_cfg */
#define UART_UTX_RS485_CFG_OFFSET                               (0x54)
#define UART_CR_UTX_RS485_EN                                    UART_CR_UTX_RS485_EN
#define UART_CR_UTX_RS485_EN_POS                                (0U)
#define UART_CR_UTX_RS485_EN_LEN                                (1U)
#define UART_CR_UTX_RS485_EN_MSK                                (((1U<<UART_CR_UTX_RS485_EN_LEN)-1)<<UART_CR_UTX_RS485_EN_POS)
#define UART_CR_UTX_RS485_EN_UMSK                               (~(((1U<<UART_CR_UTX_RS485_EN_LEN)-1)<<UART_CR_UTX_RS485_EN_POS))
#define UART_CR_UTX_RS485_POL                                   UART_CR_UTX_RS485_POL
#define UART_CR_UTX_RS485_POL_POS                               (1U)
#define UART_CR_UTX_RS485_POL_LEN                               (1U)
#define UART_CR_UTX_RS485_POL_MSK                               (((1U<<UART_CR_UTX_RS485_POL_LEN)-1)<<UART_CR_UTX_RS485_POL_POS)
#define UART_CR_UTX_RS485_POL_UMSK                              (~(((1U<<UART_CR_UTX_RS485_POL_LEN)-1)<<UART_CR_UTX_RS485_POL_POS))

/* 0x80 : uart_fifo_config_0 */
#define UART_FIFO_CONFIG_0_OFFSET                               (0x80)
#define UART_DMA_TX_EN                                          UART_DMA_TX_EN
#define UART_DMA_TX_EN_POS                                      (0U)
#define UART_DMA_TX_EN_LEN                                      (1U)
#define UART_DMA_TX_EN_MSK                                      (((1U<<UART_DMA_TX_EN_LEN)-1)<<UART_DMA_TX_EN_POS)
#define UART_DMA_TX_EN_UMSK                                     (~(((1U<<UART_DMA_TX_EN_LEN)-1)<<UART_DMA_TX_EN_POS))
#define UART_DMA_RX_EN                                          UART_DMA_RX_EN
#define UART_DMA_RX_EN_POS                                      (1U)
#define UART_DMA_RX_EN_LEN                                      (1U)
#define UART_DMA_RX_EN_MSK                                      (((1U<<UART_DMA_RX_EN_LEN)-1)<<UART_DMA_RX_EN_POS)
#define UART_DMA_RX_EN_UMSK                                     (~(((1U<<UART_DMA_RX_EN_LEN)-1)<<UART_DMA_RX_EN_POS))
#define UART_TX_FIFO_CLR                                        UART_TX_FIFO_CLR
#define UART_TX_FIFO_CLR_POS                                    (2U)
#define UART_TX_FIFO_CLR_LEN                                    (1U)
#define UART_TX_FIFO_CLR_MSK                                    (((1U<<UART_TX_FIFO_CLR_LEN)-1)<<UART_TX_FIFO_CLR_POS)
#define UART_TX_FIFO_CLR_UMSK                                   (~(((1U<<UART_TX_FIFO_CLR_LEN)-1)<<UART_TX_FIFO_CLR_POS))
#define UART_RX_FIFO_CLR                                        UART_RX_FIFO_CLR
#define UART_RX_FIFO_CLR_POS                                    (3U)
#define UART_RX_FIFO_CLR_LEN                                    (1U)
#define UART_RX_FIFO_CLR_MSK                                    (((1U<<UART_RX_FIFO_CLR_LEN)-1)<<UART_RX_FIFO_CLR_POS)
#define UART_RX_FIFO_CLR_UMSK                                   (~(((1U<<UART_RX_FIFO_CLR_LEN)-1)<<UART_RX_FIFO_CLR_POS))
#define UART_TX_FIFO_OVERFLOW                                   UART_TX_FIFO_OVERFLOW
#define UART_TX_FIFO_OVERFLOW_POS                               (4U)
#define UART_TX_FIFO_OVERFLOW_LEN                               (1U)
#define UART_TX_FIFO_OVERFLOW_MSK                               (((1U<<UART_TX_FIFO_OVERFLOW_LEN)-1)<<UART_TX_FIFO_OVERFLOW_POS)
#define UART_TX_FIFO_OVERFLOW_UMSK                              (~(((1U<<UART_TX_FIFO_OVERFLOW_LEN)-1)<<UART_TX_FIFO_OVERFLOW_POS))
#define UART_TX_FIFO_UNDERFLOW                                  UART_TX_FIFO_UNDERFLOW
#define UART_TX_FIFO_UNDERFLOW_POS                              (5U)
#define UART_TX_FIFO_UNDERFLOW_LEN                              (1U)
#define UART_TX_FIFO_UNDERFLOW_MSK                              (((1U<<UART_TX_FIFO_UNDERFLOW_LEN)-1)<<UART_TX_FIFO_UNDERFLOW_POS)
#define UART_TX_FIFO_UNDERFLOW_UMSK                             (~(((1U<<UART_TX_FIFO_UNDERFLOW_LEN)-1)<<UART_TX_FIFO_UNDERFLOW_POS))
#define UART_RX_FIFO_OVERFLOW                                   UART_RX_FIFO_OVERFLOW
#define UART_RX_FIFO_OVERFLOW_POS                               (6U)
#define UART_RX_FIFO_OVERFLOW_LEN                               (1U)
#define UART_RX_FIFO_OVERFLOW_MSK                               (((1U<<UART_RX_FIFO_OVERFLOW_LEN)-1)<<UART_RX_FIFO_OVERFLOW_POS)
#define UART_RX_FIFO_OVERFLOW_UMSK                              (~(((1U<<UART_RX_FIFO_OVERFLOW_LEN)-1)<<UART_RX_FIFO_OVERFLOW_POS))
#define UART_RX_FIFO_UNDERFLOW                                  UART_RX_FIFO_UNDERFLOW
#define UART_RX_FIFO_UNDERFLOW_POS                              (7U)
#define UART_RX_FIFO_UNDERFLOW_LEN                              (1U)
#define UART_RX_FIFO_UNDERFLOW_MSK                              (((1U<<UART_RX_FIFO_UNDERFLOW_LEN)-1)<<UART_RX_FIFO_UNDERFLOW_POS)
#define UART_RX_FIFO_UNDERFLOW_UMSK                             (~(((1U<<UART_RX_FIFO_UNDERFLOW_LEN)-1)<<UART_RX_FIFO_UNDERFLOW_POS))

/* 0x84 : uart_fifo_config_1 */
#define UART_FIFO_CONFIG_1_OFFSET                               (0x84)
#define UART_TX_FIFO_CNT                                        UART_TX_FIFO_CNT
#define UART_TX_FIFO_CNT_POS                                    (0U)
#define UART_TX_FIFO_CNT_LEN                                    (6U)
#define UART_TX_FIFO_CNT_MSK                                    (((1U<<UART_TX_FIFO_CNT_LEN)-1)<<UART_TX_FIFO_CNT_POS)
#define UART_TX_FIFO_CNT_UMSK                                   (~(((1U<<UART_TX_FIFO_CNT_LEN)-1)<<UART_TX_FIFO_CNT_POS))
#define UART_RX_FIFO_CNT                                        UART_RX_FIFO_CNT
#define UART_RX_FIFO_CNT_POS                                    (8U)
#define UART_RX_FIFO_CNT_LEN                                    (6U)
#define UART_RX_FIFO_CNT_MSK                                    (((1U<<UART_RX_FIFO_CNT_LEN)-1)<<UART_RX_FIFO_CNT_POS)
#define UART_RX_FIFO_CNT_UMSK                                   (~(((1U<<UART_RX_FIFO_CNT_LEN)-1)<<UART_RX_FIFO_CNT_POS))
#define UART_TX_FIFO_TH                                         UART_TX_FIFO_TH
#define UART_TX_FIFO_TH_POS                                     (16U)
#define UART_TX_FIFO_TH_LEN                                     (5U)
#define UART_TX_FIFO_TH_MSK                                     (((1U<<UART_TX_FIFO_TH_LEN)-1)<<UART_TX_FIFO_TH_POS)
#define UART_TX_FIFO_TH_UMSK                                    (~(((1U<<UART_TX_FIFO_TH_LEN)-1)<<UART_TX_FIFO_TH_POS))
#define UART_RX_FIFO_TH                                         UART_RX_FIFO_TH
#define UART_RX_FIFO_TH_POS                                     (24U)
#define UART_RX_FIFO_TH_LEN                                     (5U)
#define UART_RX_FIFO_TH_MSK                                     (((1U<<UART_RX_FIFO_TH_LEN)-1)<<UART_RX_FIFO_TH_POS)
#define UART_RX_FIFO_TH_UMSK                                    (~(((1U<<UART_RX_FIFO_TH_LEN)-1)<<UART_RX_FIFO_TH_POS))

/* 0x88 : uart_fifo_wdata */
#define UART_FIFO_WDATA_OFFSET                                  (0x88)
#define UART_FIFO_WDATA                                         UART_FIFO_WDATA
#define UART_FIFO_WDATA_POS                                     (0U)
#define UART_FIFO_WDATA_LEN                                     (8U)
#define UART_FIFO_WDATA_MSK                                     (((1U<<UART_FIFO_WDATA_LEN)-1)<<UART_FIFO_WDATA_POS)
#define UART_FIFO_WDATA_UMSK                                    (~(((1U<<UART_FIFO_WDATA_LEN)-1)<<UART_FIFO_WDATA_POS))

/* 0x8C : uart_fifo_rdata */
#define UART_FIFO_RDATA_OFFSET                                  (0x8C)
#define UART_FIFO_RDATA                                         UART_FIFO_RDATA
#define UART_FIFO_RDATA_POS                                     (0U)
#define UART_FIFO_RDATA_LEN                                     (8U)
#define UART_FIFO_RDATA_MSK                                     (((1U<<UART_FIFO_RDATA_LEN)-1)<<UART_FIFO_RDATA_POS)
#define UART_FIFO_RDATA_UMSK                                    (~(((1U<<UART_FIFO_RDATA_LEN)-1)<<UART_FIFO_RDATA_POS))

struct bflb_uart_platform_uart {
	unsigned long mapbase;
	unsigned int irq;
};

#endif /* _BFLB_UART_H_ */
